name: PR Cleanup

run-name: "PR Cleanup #${{ github.event.pull_request.number }} / ${{ github.event.pull_request.head.sha }}"

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    if: github.event.pull_request.base.ref == github.event.repository.default_branch
    uses: splrad/steward/.github/workflows/pr-cleanup.yml@f99aa6d1dd0e4d391eeec1282c296a6f020f40ba
    with:
      app_client_id: ${{ vars.WORKFLOW_AUTOMATION_APP_CLIENT_ID }}
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      app_private_key: ${{ secrets.WORKFLOW_AUTOMATION_APP_PRIVATE_KEY }}
